### ISSUE TITLE
The "auto duel" feature keep running after i turn off the program

### ISSUE THREAD

**Issue by congson95dev** [BullyWiiPlaza/JMaster-Duel-Bot#70] opened 2024-08-04 14:09 UTC
Even though i've click on "X" button to stop the bot (JMaster Duel Bot) program, but the bot still auto dueling for me, seem like it running on the background or something like that.
Please check and fix this issue.

**Comment by BullyWiiPlaza** [comment] 2024-08-04 16:43
Yes, obviously, you need to disable "Run Duel Bot" first. Closing the program doesn't do that, like with most other options. That's normal and not a bug.

**Closed as completed by BullyWiiPlaza** 2024-08-04 16:43 UTC
Labels: invalid
