### ISSUE TITLE
DLL Saliva injector not found

### ISSUE THREAD

**Issue by ninjagod888** [BullyWiiPlaza/JMaster-Duel-Bot#61] opened 2024-05-03 16:15 UTC
![immagine_2024-05-03_181255618](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/139118894/b751e59a-faf9-4f03-8c82-a463472016e2)

Hi I was trying the bot for the first time and I can't get anything that is not this pop up window telling me that is not possible to run "saliva-injector.dll" i couldn't find anything online, is there a way to fix this?

**Comment by ninjagod888** [comment] 2024-05-03 16:18
Ok, after some spamming on the OK button I managed to get this prompt
![immagine_2024-05-03_181719997](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/139118894/4f13fc89-222c-4a6c-8b7f-858f0707080a)
 java.util.concurrent.TimeoutException: Process C:\WINDOWS\system32\rundll32.exe did not exit in a reasonable amount of time (60 seconds):

	at AB.j(ok:145)
	at Hb.j(ae:519)
	at lpt7.j(te:168)
	at dB.A(fe:578)
	at dB.G(fe:2078)
	at Qa.ka(wj:2450)
	at Qa.<init>(wj:394)
	at MasterDuelBotClient.j(hl:444)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BullyWiiPlaza** [comment] 2024-05-03 19:30
Hello @ninjagod888,

thanks for letting me know the error you're facing. In general, it works fine so the issue is on your end. I suspect it's an Antivirus detection/issue. Please try to add an exception for the DLL or try to disable your Antivirus completely temporarily and see if it works without error.

**Comment by ninjagod888** [comment] 2024-05-03 21:25
Hi, I alredy checked the antivirus, and it didn't blocked anything today, i even tried to run this using another version of java or to use another older version of this software, but nothing seems to work, it always give me that error

**Comment by BullyWiiPlaza** [comment] 2024-08-04 16:54
This issue seems to be specific to you and cannot be reproduced by me or pretty much anyone else, so I'm closing this issue. I hope that you managed to find a fix if you still cared about it. Most likely using a different machine or re-installing Windows does the trick as well.

**Closed as completed by BullyWiiPlaza** 2024-08-04 16:54 UTC
Labels: bug
