### ISSUE TITLE
Windows 10 Crash only on 2nd Duel

### ISSUE THREAD

**Issue by randoomdude** [BullyWiiPlaza/JMaster-Duel-Bot#68] opened 2024-06-02 22:51 UTC
For some reason I have a very weird issue on just my alt steam account where Jmaster Bot will run, I've tried a thread count 8/12 and checking reuse cache on/off, seems odd since both share the same steam folder

--------------------------------------------------------
copied just a couple seconds after it crashes on the 2nd duel, which always happens after the coin flip, when the field first loads and the big DUEL flashes across screen

[INFO ] 15:34:08.120 [GUI Thread]: Launching GUI...
[INFO ] 15:34:08.827 [GUI Thread]: Configuring frame properties...
[INFO ] 15:34:08.993 [GUI Thread]: Configuring application tabs...
[INFO ] 15:34:08.994 [GUI Thread]: Configuring cheats tabs...
[INFO ] 15:34:09.014 [GUI Thread]: Configuring settings tabs...
[INFO ] 15:34:09.239 [Application Validator]: Performing application validation...
[INFO ] 15:34:09.288 [Player Latency Reader]: Injecting Master Drool Saliva...
[INFO ] 15:34:11.424 [Operating System Printer]: Operating system: Microsoft Windows 10 Pro
[INFO ] 15:34:14.558 [Player Latency Reader]: Master Drool Saliva successfully injected...
[INFO ] 15:34:16.046 [GUI Thread]: Configuring bot tabs...
[INFO ] 15:34:16.203 [GUI Thread]: Configuring card search tabs...
[INFO ] 15:34:16.205 [Card Database Updater]: Starting "Card Database Updater" thread...
[INFO ] 15:34:16.211 [GUI Thread]: Configuring donator tabs...
[INFO ] 15:34:16.264 [GUI Thread]: Configuring about tabs...
[INFO ] 15:34:16.273 [GUI Thread]: Configuring process controls tabs...
[INFO ] 15:34:16.296 [Donator Authentication Checker]: Generating license key...
[INFO ] 15:34:18.755 [GUI Thread]: Authenticated successfully...
[INFO ] 15:34:19.193 [Process Interaction Button Availability Setter]: Injecting speed hack...
[INFO ] 15:34:20.517 [Process Interaction Button Availability Setter]: Setting speed hack speed to: 1.2x
[INFO ] 15:35:16.214 [Card Database Updater]: Parsing card database from memory...
[INFO ] 15:35:16.215 [Card Database Updater]: Reading card ids...
[INFO ] 15:35:16.227 [Card Database Updater]: Reading card names...
[ERROR] 15:36:17.921 [Card Database Updater]: Updating card database failed
java.io.IOException: Search pattern not found
	at ja.H(hn:590) ~[qzegLA976qaHaPzioyv1:?]
	at ja.E(hn:565) ~[qzegLA976qaHaPzioyv1:?]
	at D.S(sh:2080) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 15:36:18.241 [Deck Tracker Updater]: 
Lpt6: 2024-06-02 15:36:18.236 (   0.321s) [                ] BotUtilitiesClient.cpp:790    ERR| Failed to find main window handle

	at lpT4.i(id:581) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:415) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:256) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:54) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:32) ~[qzegLA976qaHaPzioyv1:?]
	at D.c(sh:644) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 15:36:19.254 [Process Interaction Button Availability Setter]: 
Lpt6: 2024-06-02 15:36:19.247 (   0.264s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at lpT4.i(id:581) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:415) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:256) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:54) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:32) ~[qzegLA976qaHaPzioyv1:?]
	at D.K(sh:2818) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 15:36:19.375 [Process Interaction Button Availability Setter]: 
Lpt6: Finding process by process name: -1
Process id for process name not found

	at lpT4.i(id:581) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.j(nj:284) ~[qzegLA976qaHaPzioyv1:?]
	at D.K(sh:3047) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 15:36:20.308 [Player Latency Reader]: 
Lpt6: 2024-06-02 15:36:20.304 (   0.240s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at lpT4.i(id:581) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:415) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:256) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:54) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:32) ~[qzegLA976qaHaPzioyv1:?]
	at D.g(sh:4117) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 15:36:20.560 [Process Interaction Button Availability Setter]: 
Lpt6: Finding process by process name: -1
Process id for process name not found

	at lpT4.i(id:581) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.j(nj:284) ~[qzegLA976qaHaPzioyv1:?]
	at D.K(sh:3047) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 15:36:21.455 [Duel Spy Updater]: 
Lpt6: 2024-06-02 15:36:21.448 (   0.299s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at lpT4.i(id:581) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:415) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.i(nj:256) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:54) ~[qzegLA976qaHaPzioyv1:?]
	at ja.i(hn:32) ~[qzegLA976qaHaPzioyv1:?]
	at D.ma(sh:1204) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 15:36:21.807 [Process Interaction Button Availability Setter]: 
Lpt6: Finding process by process name: -1
Process id for process name not found

	at lpT4.i(id:581) ~[qzegLA976qaHaPzioyv1:?]
	at Vb.j(nj:284) ~[qzegLA976qaHaPzioyv1:?]
	at D.K(sh:3047) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]

**Comment by BullyWiiPlaza** [comment] 2024-06-03 17:48
Hello @randoomdude,

the log didn't help me identify anything but since I ran into more or less the same issue I was able to resolve it I believe. Please restart the bot and see if no more crashes occur in solo duels.

Thanks!

**Comment by randoomdude** [comment] 2024-06-11 05:48
Happened again on another account, have some more info as to why I think. I looks like if you turn on 'Force Replay Controls' and try to play during PvP (I tried during the qualifier cup) the game will crash, and then continue crashing in every PvP match even if you uncheck it. Maybe Force Replay Control is setting of some anti-cheat in PvP but at any rate I don't think it's working and don't know how to play PvP matches anymore, I hope you cann look into it

_____________________________

Log from after it stopped working properly:
[INFO ] 22:32:53.032 [GUI Thread]: Launching GUI...
[INFO ] 22:32:53.749 [GUI Thread]: Configuring frame properties...
[INFO ] 22:32:53.912 [GUI Thread]: Configuring application tabs...
[INFO ] 22:32:53.913 [GUI Thread]: Configuring cheats tabs...
[INFO ] 22:32:53.934 [GUI Thread]: Configuring settings tabs...
[INFO ] 22:32:54.166 [Application Validator]: Performing application validation...
[INFO ] 22:32:54.220 [Player Latency Reader]: Injecting Master Drool Saliva...
[INFO ] 22:32:55.951 [Operating System Printer]: Operating system: Microsoft Windows 10 Pro
[INFO ] 22:32:59.411 [Player Latency Reader]: Master Drool Saliva successfully injected...
[INFO ] 22:33:00.489 [GUI Thread]: Configuring bot tabs...
[INFO ] 22:33:00.585 [GUI Thread]: Configuring card search tabs...
[INFO ] 22:33:00.591 [GUI Thread]: Configuring donator tabs...
[INFO ] 22:33:00.642 [GUI Thread]: Configuring about tabs...
[INFO ] 22:33:00.651 [GUI Thread]: Configuring process controls tabs...
[INFO ] 22:33:00.670 [Donator Authentication Checker]: Generating license key...
[INFO ] 22:33:02.745 [GUI Thread]: Authenticated successfully...
[INFO ] 22:33:04.054 [Process Interaction Button Availability Setter]: Injecting speed hack...
[INFO ] 22:33:04.939 [Process Interaction Button Availability Setter]: Setting speed hack speed to: 1.2000000000000002x
[INFO ] 22:33:05.637 [GUI Thread]: Setting "Force Replay Controls (Donator only)" to: true
[INFO ] 22:33:09.054 [GUI Thread]: Setting "Force Replay Controls (Donator only)" to: false
[INFO ] 22:43:02.749 [Donator Authentication Checker]: Generating license key...
[INFO ] 22:43:03.520 [GUI Thread]: Authenticated successfully...
[ERROR] 22:44:01.618 [Duel Spy Updater]: 
Lpt4: 2024-06-10 22:44:01.612 (   0.306s) [                ] BotUtilitiesClient.cpp:790    ERR| Failed to find main window handle

	at HA.C(bd:491) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.C(nl:1195) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.C(nl:273) ~[qzegLA976qaHaPzioyv1:?]
	at ob.C(th:209) ~[qzegLA976qaHaPzioyv1:?]
	at ob.H(th:104) ~[qzegLA976qaHaPzioyv1:?]
	at lPT7.M(rd:1246) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 22:44:02.692 [Player Latency Reader]: 
Lpt4: 2024-06-10 22:44:02.687 (   0.300s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at HA.C(bd:491) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.C(nl:1195) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.C(nl:273) ~[qzegLA976qaHaPzioyv1:?]
	at ob.C(th:209) ~[qzegLA976qaHaPzioyv1:?]
	at ob.H(th:104) ~[qzegLA976qaHaPzioyv1:?]
	at lPT7.B(rd:4041) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 22:44:03.759 [Process Interaction Button Availability Setter]: 
Lpt4: 2024-06-10 22:44:03.755 (   0.296s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at HA.C(bd:491) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.C(nl:1195) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.C(nl:273) ~[qzegLA976qaHaPzioyv1:?]
	at ob.C(th:209) ~[qzegLA976qaHaPzioyv1:?]
	at ob.H(th:104) ~[qzegLA976qaHaPzioyv1:?]
	at lPT7.O(rd:3094) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 22:44:03.853 [Process Interaction Button Availability Setter]: 
Lpt4: Finding process by process name: -1
Process id for process name not found

	at HA.C(bd:491) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.H(nl:372) ~[qzegLA976qaHaPzioyv1:?]
	at lPT7.O(rd:3069) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 22:44:05.037 [Process Interaction Button Availability Setter]: 
Lpt4: Finding process by process name: -1
Process id for process name not found

	at HA.C(bd:491) ~[qzegLA976qaHaPzioyv1:?]
	at LPT6.H(nl:372) ~[qzegLA976qaHaPzioyv1:?]
	at lPT7.O(rd:3069) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]

**Comment by BullyWiiPlaza** [comment] 2024-06-12 12:45
> I looks like if you turn on 'Force Replay Controls' and try to play during PvP (I tried during the qualifier cup) the game will crash [...]

"Force Replay Controls" works normally for me, screenshot:
![image](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/7620135/a2cee99d-51df-4b72-8fca-fc03fcf5d025)
So I'm not sure how that would cause any crash, then.

> and then continue crashing in every PvP match even if you uncheck it

If you uncheck it, it's disabled. It does not have any more effects on the game. If you restarted the game, it will not be re-enabled again if the checkbox is unchecked. Not sure how that would be the causes of anything then?

---

Also, the logs you posted are not meaningful for the issue you're mentioning.

**Comment by BullyWiiPlaza** [comment] 2024-08-04 16:55
Either the issue is no longer reproducible or it's no longer relevant. I'm closing this issue, let me know if you have any other problems.

**Closed as completed by BullyWiiPlaza** 2024-08-04 16:55 UTC
Labels: bug
